apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  db-pass: dnByb2RicGFzcw== # echo -n 'vprodbpass' | base64    docker/src/main/resources/application.properties
  rmq-pass: Z3Vlc3Q= # echo -n 'guest' | base64    docker/src/main/resources/application.properties
