apiVersion: v1
kind: Service
metadata:
  name: vprocache01 #src/main/resources/application.properties ligne 9
spec:
  ports: # map avec backend et conteneur
  - port: 11211 #src/main/resources/application.properties ligne 10
    targetPort: vpromc-port
    protocol: TCP
  selector:
    app: vpromc # kubernetes/vpro-app/mcdep.yml ligne 6
  type: ClusterIP
